### ISSUE TITLE
Make an embedded calendar

### ISSUE THREAD

**Issue by ljchang** [Summer-MIND/Summer-MIND.github.io#7]
It would be nice to be able to embed google calendar, or parse info from their API so that we can more easily keep schedule up to date.

**Comment by jeremymanning** [comment]
maybe something like this?  https://fullcalendar.io/download

**Comment by yarikoptic** [comment]
I have embedded Google calendar before - worked nicely iirc. What do you mean by "more easily keep schedule up to date."? Google calendar webui seems to be quite flexible/easy to manipulate. Something like  https://github.com/insanum/gcalcli could be used to assist manipulating it via cmdline if needed

**Comment by ljchang** [comment]
thanks @yarikoptic, gcalcli looks really cool!  Unfortunately, this is a static site, so I think we need to rely on javascript stuff.  But I'm definitely going to use that for other things.

Basically, it seems like there are 3 options:

1) just embed the calendar using an iframe.  Super easy, but kind of ugly and lacks a lot of customization.
https://gist.github.com/iani/8906741

2) We could make "event" pages and write a parser to add this to a customizable javascript calendar:  https://www.raymondcamden.com/2017/02/24/an-example-of-a-static-site-with-a-dynamic-calendar

3) We could make a events.csv with all of the events in a spreadsheet and parse that.

**Comment by ljchang** [comment]
I just went with the embedded one for now, we can revisit later.  https://github.com/Summer-MIND/Summer-MIND.github.io/commit/1b8c8d2137e5d6efdd871e4ab8c4971d2b624fc2
